title: "CFET"
name: "Center for Free Economic Thought"
# subtitle: "Center for Free Economic Thought."
email: cfet@ebs.ee
description: >- # this means to ignore newlines until "baseurl:"
  The Center for Free Economic Thought at Estonian Business School is an independent and non-partisan think-tank.
url: "https://www.cfet.ee"
repository: "MissionLiberty/cfet.ee"
#twitter_username: missionliberty.ee
github_username:  MissionLiberty
timezone: Europe/Tallinn
logo: /img/CFET_logo_128.png
og_image: /img/CFET_logo_128.png

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # find more from
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache
include: ["_pages"]
exclude:
   - README.md

#GitHub defaults
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
